// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 4/7/2026, 8:41:24 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.ts";
import cfg3 from "./../../tailwind.config.ts";
const config = [
{"content":{"files":["/workspace/fitpulse/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/workspace/fitpulse/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/workspace/fitpulse/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/workspace/fitpulse/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/workspace/fitpulse/plugins/**/*.{js,ts,mjs}","/workspace/fitpulse/composables/**/*.{js,ts,mjs}","/workspace/fitpulse/utils/**/*.{js,ts,mjs}","/workspace/fitpulse/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/workspace/fitpulse/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/workspace/fitpulse/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/workspace/fitpulse/app.config.{js,ts,mjs}"]}},
{},
cfg2,
cfg3
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;